import {_electron as electron,expect} from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
const root=process.cwd();
const packaged=process.argv.includes('--packaged');
const qa=path.join(root,'data','qa',`electron-${packaged?'packaged':'development'}-${Date.now()}`);
await fs.mkdir(qa,{recursive:true});
const app=await electron.launch({executablePath:packaged?path.join(process.env.BLACKWIRE_PACKAGED_DIR||path.join(root,'release','win-unpacked'),'Black Wire Technical Reference Guide.exe'):path.join(root,'node_modules','electron','dist','electron.exe'),args:packaged?[]:[root],env:{...process.env,BLACKWIRE_TEST_DATA:qa},timeout:60000});
const errors=[];
try{
 const page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));
 await expect(page.getByRole('heading',{name:/Know your board/})).toBeVisible({timeout:60000});
 expect(page.url()).toBe('blackwire://app/index.html');
 expect(await page.evaluate(()=>typeof window.require)).toBe('undefined');
 expect(await page.evaluate(()=>window.blackwire.platform)).toBe('win32');
 const catalog=await page.evaluate(()=>fetch('/catalog.json').then(r=>r.json()));
 expect(catalog.stats.referenceEntries).toBe(catalog.boards.reduce((n,b)=>n+b.assets.length,0));
 const pdfBoard=catalog.boards.find(b=>b.assets.some(a=>a.extension==='pdf')&&b.assets.some(a=>a.type==='pinout image'));
 const pdf=pdfBoard.assets.find(a=>a.extension==='pdf');
 const pdfStatus=await page.evaluate(async file=>{const r=await fetch('/library/'+file);return {status:r.status,type:r.headers.get('content-type'),signature:new TextDecoder().decode((await r.arrayBuffer()).slice(0,5))};},pdf.file);
 expect(pdfStatus.status).toBe(200);expect(pdfStatus.signature).toBe('%PDF-');expect(pdfStatus.type).toContain('application/pdf');
 const invalid=await page.evaluate(async()=>{try{await window.blackwire.openOriginal('../package.json');return false;}catch{return true;}});expect(invalid).toBe(true);
 await page.getByRole('textbox',{name:'Search boards and references'}).fill('teensy 4.1');
 await page.getByRole('button',{name:'View Teensy 4.1 references',exact:true}).click();
 let dialog=page.getByRole('dialog',{name:'Teensy 4.1 references'});
 await expect.poll(()=>dialog.locator('.scaled-image img').evaluate(img=>img.complete&&img.naturalWidth>0)).toBe(true);
 await dialog.getByRole('button',{name:'Save board',exact:true}).click();
 await expect.poll(async()=>JSON.parse(await fs.readFile(path.join(qa,'workbench.json'),'utf8')).favorites.length).toBe(1);
 const savePath=path.join(qa,'saved-reference.png');
 await app.evaluate(({dialog},savePath)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:savePath});},savePath);
 await dialog.getByRole('button',{name:'Save original',exact:true}).click();
 const board=catalog.boards.find(b=>b.name==='Teensy 4.1');
 await expect.poll(async()=>{try{return crypto.createHash('sha256').update(await fs.readFile(savePath)).digest('hex');}catch{return '';}}).toBe(board.assets[0].hash);
 await page.keyboard.press('Escape');await page.reload();
 await page.getByRole('button',{name:'Saved boards',exact:false}).click();await expect(page.locator('.board-card')).toHaveCount(1);
 await page.getByRole('button',{name:'Board library',exact:false}).click();
 await page.getByRole('textbox',{name:'Search boards and references'}).fill(pdfBoard.name);
 await page.getByRole('button',{name:`View ${pdfBoard.name} references`,exact:true}).click();
 dialog=page.getByRole('dialog',{name:`${pdfBoard.name} references`});
 const label=pdf.label;await dialog.locator('.asset-list button').filter({hasText:label}).first().click();
 await expect(dialog.locator('canvas[data-rendered="true"]')).toBeVisible({timeout:30000});
 await dialog.getByRole('button',{name:'Next page',exact:true}).click();
 await expect(dialog.getByRole('status')).toHaveText('Page 2 of 7');
 await expect(dialog.locator('canvas[data-rendered="true"]')).toBeVisible();
 await dialog.getByRole('button',{name:'Zoom in',exact:true}).click();
 await expect(dialog.locator('.zoom-value')).toHaveText('125%');
 await expect(dialog.locator('canvas[data-rendered="true"]')).toBeVisible();
 await page.screenshot({path:path.join(qa,'native-pdf.png')});
 await page.keyboard.press('Escape');await page.getByRole('button',{name:'Black Wire home'}).click();
 await page.screenshot({path:path.join(qa,'native-library.png')});
 await page.getByRole('button',{name:'About the guide',exact:true}).click();
 await page.getByText('Original application code — MIT',{exact:true}).click();
 await expect(page.locator('.license-notices pre').first()).toContainText('Copyright (c) 2026 Kal (Your Pal Kal) / Valleytech Solutions');
 await page.getByText('Original guide material — CC BY 4.0',{exact:true}).click();
 await expect(page.locator('.license-notices pre').nth(1)).toContainText('Creative Commons Attribution 4.0 International Public License');
 await page.screenshot({path:path.join(qa,'native-licenses.png')});
 await page.getByRole('button',{name:/Displays & modules/}).click();
 await page.getByRole('textbox',{name:'Search boards and references'}).fill('BME280');
 await expect(page.locator('.maker-card').first()).toContainText('BME280');
 await page.locator('.maker-card').filter({hasText:'Adafruit'}).getByRole('button',{name:/Open maker record/}).first().click();
 await expect(page.getByRole('dialog')).toContainText('Documented pin labels');
 await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Reset search & filters'}).click();
 await page.evaluate(()=>window.scrollTo(0,0));
 await page.screenshot({path:path.join(qa,'native-makers.png')});
 expect(catalog.stats.makerRecords).toBe(457);
 expect(errors).toEqual([]);
 const report={packaged,catalog:catalog.stats,pdf:pdfBoard.name,checks:['custom protocol','renderer isolation','PDF delivery','offline image decoding','path whitelist','native save original hash','saved boards persistence','PDF viewer'],qa,passed:true};
 await fs.writeFile(path.join(qa,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await app.close();}
