import fs from 'node:fs/promises';
import path from 'node:path';
import {articles, makerIntros} from '../data/wiki.mjs';
import {coverageLabels} from '../src/pin-coverage.mjs';

const site='https://valleytech-black-wire-guide.pages.dev';
const title="The Black Wire Maker's Technical Reference Guide";
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const link=(url,label)=>`<a href="${escape(url)}">${escape(label)}</a>`;
const list=(items,ordered=false)=>{const tag=ordered?'ol':'ul';return `<${tag}>${items.map(s=>`<li>${escape(s)}</li>`).join('')}</${tag}>`;};

export async function buildWiki(out,base='/') {
 const catalog=JSON.parse(await fs.readFile('public/catalog.json','utf8'));
 const paths=[];
 const page=async(route,name,description,body,type='WebPage')=>{
  const url=site+base+route;
  const schema={'@context':'https://schema.org','@type':type,name,description,url,isPartOf:{'@type':'WebSite',name:title,url:site+'/'}};
  const html=`<!doctype html><html lang="en" data-theme="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(name)} | Black Wire</title><meta name="description" content="${escape(description)}"><meta name="theme-color" content="#151514"><link rel="canonical" href="${url}"><meta property="og:type" content="website"><meta property="og:title" content="${escape(name)} | Black Wire"><meta property="og:description" content="${escape(description)}"><meta property="og:url" content="${url}"><meta property="og:image" content="${site}/brand/social-card.png"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="${base}brand/black-wire-red.png"><script src="${base}theme-init.js"></script><link rel="stylesheet" href="${base}wiki.css"><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script><script defer src="${base}wiki.js"></script></head><body><a class="skip-link" href="#content">Skip to content</a><header class="wiki-header"><a class="wiki-brand" href="${base}"><img src="${base}brand/black-wire-red.png" alt="Black Wire" width="34" height="40"><span>${escape(title)}<small>REFERENCE WIKI · FIRST EDITION / 2026</small></span></a><nav aria-label="Wiki navigation">${link(base+'wiki/','Wiki')}${link(base+'wiki/boards/','Boards')}${link(base+'wiki/modules/','Modules')}${link(base,'Open guide')}<button class="wiki-theme" aria-label="Toggle light and dark mode" hidden>Light mode</button></nav></header><main id="content"><p class="kicker">A VALLEYTECH SOLUTIONS PROJECT</p><h1>${escape(name)}</h1><p class="intro">${escape(description)}</p>${body}</main><footer>${link(base+'wiki/coverage-and-sources/','Coverage & sources')} · ${link(base+'wiki/contributing/','Contribute')} · ${link('https://github.com/valleytechsolutions/black-wire-desktop/releases/latest','Desktop downloads')}<p>Original guide text by Kal / Valleytech Solutions. Source artwork retains its own rights. App 0.6.0 · collection ${escape(catalog.editionInfo.snapshot)}.</p></footer></body></html>`;
  const dest=path.join(out,route,'index.html');await fs.mkdir(path.dirname(dest),{recursive:true});await fs.writeFile(dest,html);paths.push(url);
 };
 const cards=items=>`<div class="wiki-grid">${items.map(({url,title,description})=>`<a class="wiki-card" href="${escape(url)}"><h2>${escape(title)} <span aria-hidden="true">↗</span></h2><p>${escape(description)}</p></a>`).join('')}</div>`;
 await page('wiki/','The maker reference wiki','Find a reference, understand its limits and get back to building. Guides and catalog directories you can read without opening the app.',cards(articles.map(a=>({...a,url:base+'wiki/'+a.slug+'/'})))+`<h2>Browse the catalog</h2>`+cards([{url:base+'wiki/boards/',title:'Board & device directory',description:`${catalog.boards.length.toLocaleString('en-US')} board and device listings, grouped by family, with documentation status.`},{url:base+'wiki/modules/',title:'Displays, sensors & modules',description:`${catalog.makerParts.length} maker records, grouped by purpose, including power and charging.`}])+`<p class="note">These counts include family records and documentation gaps. They are not a count of fully verified pinouts. ${link(base+'wiki/coverage-and-sources/','Read the coverage policy')}.</p>`);
 for(const a of articles){
  const content=a.sections.map(s=>`<section><h2>${escape(s.heading)}</h2>${s.text?`<p>${escape(s.text)}</p>`:''}${s.items?list(s.items):''}${s.steps?list(s.steps,true):''}${(s.links||[]).map(([label,url])=>`<p class="source-link">${link(url,label)} ↗</p>`).join('')}</section>`).join('');
  await page('wiki/'+a.slug+'/',a.title,a.description,`<article>${content}</article><p class="next-link">${link(base,'Open the reference guide →')} · ${link(base+'wiki/','All wiki topics')}</p>`);
 }
 const recordTable=(records,kind)=>`<label class="directory-search" hidden>Filter this directory <input type="search" placeholder="Model, brand or interface" aria-label="Filter this directory"></label><p class="directory-count" role="status"></p><div class="directory-table"><table><thead><tr><th scope="col">Model / manufacturer</th><th scope="col">Family / interface</th><th scope="col">Reference coverage</th></tr></thead><tbody>${[...records].sort((a,b)=>(a.brand+' '+a.name).localeCompare(b.brand+' '+b.name)).map(r=>`<tr><td>${link(base+(kind==='maker'?'?tab=makers&part=':'?board=')+encodeURIComponent(r.id),r.name)}<small>${escape(r.brand)} · ${escape(r.revision||'Revision not identified')}</small></td><td>${escape(kind==='maker'?(r.interfaces||[]).join(' / ')||r.technology||'See record':r.processor||r.family)}${kind==='maker'&&r.resolution?`<small>${escape(r.resolution)}</small>`:''}</td><td><span class="status">${escape(coverageLabels[r.pinoutCoverage?.status]||'Documentation needed')}</span><small>${r.assets?.length||0} reference files · ${(r.pinoutCoverage?.purposeRows)||0} documented purpose rows</small></td></tr>`).join('')}</tbody></table></div>`;
 const boardIntros={CYD:'ESP32 display boards commonly grouped under CYD. Connector and display revisions differ; match the complete model code.',ESP32:'ESP32 and ESP8266 development boards. Match the module, board revision and USB or header layout.',RP2040:'RP2040 development boards and products. A shared microcontroller does not mean a shared header.',RP2350:'RP2350 development boards and products. Compare the exact board and revision.',Teensy:'Teensy boards and reference documents. Use the exact version, including any suffix.','Raspberry Pi SBC':'Raspberry Pi computers. Physical header numbering and GPIO signal numbers are different.','Other SBC':'Single-board computers from additional manufacturers. Connector assignments are model-specific.',Expansion:'Expansion, adapter and radio boards. Read host compatibility and connector scope.','GPIO device':'Devices exposing pins or GPIO. Match connector orientation and model revision.',Other:'Additional development boards. Search within this directory by model or manufacturer.','Source collection':'Manufacturer source records awaiting more detailed identification or review. A source record does not mean a complete pinout.','Chip reference':'Chip-package references. These locate contacts on the IC package and must not be treated as development-board header maps.'};
 for(const [kind,records,field,root,label,intros] of [['board',catalog.boards,'family','boards','Board & device directory',boardIntros],['maker',catalog.makerParts,'category','modules','Displays, sensors & modules',makerIntros]]){
  const groups=[...new Set(records.map(r=>r[field]))].sort();
  await page(`wiki/${root}/`,label,`Browse ${records.length.toLocaleString('en-US')} catalog listings with source coverage and direct links to their references.`,cards(groups.map(g=>({url:base+`wiki/${root}/${slug(g)}/`,title:g,description:`${records.filter(r=>r[field]===g).length} records. ${intros[g]||'Compare the exact model and revision.'}`})))+`<p class="note">A listing may be an exact model, a family, or an identification task. Coverage is shown for each record; no all-device completeness is implied.</p>`,'CollectionPage');
  for(const g of groups)await page(`wiki/${root}/${slug(g)}/`,g+' references',intros[g]||`Find ${g} references in the Black Wire guide.`,recordTable(records.filter(r=>r[field]===g),kind)+`<p class="note">Physical source availability does not establish all-pin completeness or electrical compatibility. ${link(base+'wiki/coverage-and-sources/','Read the coverage labels')}.</p>`,'CollectionPage');
 }
 await fs.writeFile(path.join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${[site+base,...paths].map(url=>`<url><loc>${escape(url)}</loc></url>`).join('')}</urlset>`);
 await fs.writeFile(path.join(out,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${site}${base}sitemap.xml\n`);
 const index=path.join(out,'index.html');
 if(base!=='/')await fs.writeFile(index,(await fs.readFile(index,'utf8')).replaceAll('href="/wiki/',`href="${base}wiki/`).replaceAll('src="/theme-init.js"',`src="${base}theme-init.js"`).replaceAll(site+'/',site+base));
 console.log(`Built ${paths.length} static wiki and directory pages with sitemap.`);
 return paths;
}

export async function buildWikiMarkdown(out='docs/wiki') {
 await fs.mkdir(out,{recursive:true});
 for(const a of articles){
  const text=`# ${a.title}\n\n${a.description}\n\n`+a.sections.map(s=>`## ${s.heading}\n\n${s.text?s.text+'\n\n':''}${(s.items||s.steps||[]).map((t,i)=>(s.steps?`${i+1}. `:'- ')+t).join('\n')}${(s.items||s.steps)?'\n\n':''}${(s.links||[]).map(([t,u])=>`[${t}](${u})`).join(' · ')}`).join('\n\n')+`\n\n[Read the public wiki](${site}/wiki/${a.slug}/) · [Open the guide](${site}/)\n`;
  await fs.writeFile(path.join(out,a.slug+'.md'),text);
 }
 await fs.writeFile(path.join(out,'Home.md'),`# The Black Wire Maker's Technical Reference Guide\n\nKnow your board. Make the connection.\n\n[Open the guide](${site}/) · [Public reference wiki](${site}/wiki/) · [Windows downloads](https://github.com/valleytechsolutions/black-wire-desktop/releases/latest)\n\n${articles.map(a=>`- [${a.title}](${a.slug}.md) — ${a.description}`).join('\n')}\n\n[Board directory](${site}/wiki/boards/) · [Displays, sensors & modules](${site}/wiki/modules/)\n\nFirst Edition / 2026. Coverage includes incomplete and family records; see the coverage policy.\n`);
}
