import React,{useMemo,useState} from 'react';
import {Radio,Search,Clock,Layers} from 'lucide-react';
import {searchBoards,normalize} from './domain.mjs';

export default function DevicesView({catalog,query,favorites,toggleFavorite,open,BoardCard,SourceLink}){
 const [category,setCategory]=useState(''),[brand,setBrand]=useState(''),[processor,setProcessor]=useState(''),[pinoutsOnly,setPinoutsOnly]=useState(false),[limit,setLimit]=useState(30);
 const devices=useMemo(()=>catalog.boards.filter(b=>b.device&&b.assets.length),[catalog]);
 const categories=[...new Set(devices.map(b=>b.device.category))].sort();
 const brands=[...new Set(devices.map(b=>b.brand))].sort();
 const processors=[...new Set(devices.map(b=>b.processor).filter(Boolean))].sort();
 const matches=useMemo(()=>searchBoards(catalog.boards,{query,brand,processor,devicesOnly:true,deviceCategory:category}).filter(b=>!pinoutsOnly||b.pinouts>0),[catalog,query,brand,processor,category,pinoutsOnly]);
 React.useEffect(()=>setLimit(30),[query,brand,processor,category,pinoutsOnly]);
 const watchlist=(catalog.deviceWatchlist||[]).filter(b=>(!brand||b.brand===brand)&&(!processor||b.processor===processor)&&(!category||b.category===category)&&(!query.trim()||normalize([b.name,b.brand,b.processor,...(b.aliases||[])].join(' ')).includes(normalize(query))));
 function reset(){setCategory('');setBrand('');setProcessor('');setPinoutsOnly(false);}
 return <div className="devices-page">
  <section className="devices-hero"><div><div className="eyebrow"><span className="status-square"/>FIRST EDITION · THE CONNECTED WORKBENCH</div><h1>Small devices.<br/>Big possibilities<span className="lime-period">.</span></h1><p>Find the pins behind your handheld, radio, wearable or smart display. Original diagrams, organized by the device in your hands.</p><div className="device-examples">T-Embed <span>↗</span> T-Beam <span>↗</span> Cardputer <span>↗</span> Flipper Zero</div></div><div className="device-hero-card"><Radio size={38}/><span>DEVICES & IoT</span><strong>{devices.length.toLocaleString()}</strong><p>device records with references<br/>{brands.length} manufacturers & source groups</p><div><span className="status-square"/>SOURCE IMAGES · EXACT MODELS</div></div></section>
  <div className="edition-note"><Layers size={18}/><p><b>First Edition / 2026</b> · Digital collection {catalog.editionInfo?.snapshot||'2026.09.2'}. New references and corrections update this edition. Annual book editions will have their own frozen snapshots.</p></div>
  <section className="device-library"><div className="section-heading"><div><div className="eyebrow">FIND YOUR DEVICE</div><h2>From pocket tools to field nodes</h2></div><span className="device-total">{matches.length} matching devices</span></div>
   <div className="device-categories" aria-label="Device categories">{['',...categories].map(c=><button key={c} aria-pressed={category===c} className={category===c?'selected':''} onClick={()=>setCategory(c)}>{c||'All devices'}<span>{devices.filter(b=>!c||b.device.category===c).length}</span></button>)}</div>
   <div className="filter-bar device-filters">{[['Manufacturer',brand,setBrand,brands],['Microcontroller',processor,setProcessor,processors]].map(([label,value,set,options])=><label className="select-field" key={label}><span>{label}</span><select aria-label={'Device '+label.toLowerCase()} value={value} onChange={e=>set(e.target.value)}><option value="">All {label==='Manufacturer'?'manufacturers':'microcontrollers'}</option>{options.map(o=><option key={o}>{o}</option>)}</select></label>)}<label className="device-pinout-toggle"><input type="checkbox" checked={pinoutsOnly} onChange={e=>setPinoutsOnly(e.target.checked)}/>Pinout images only</label>{(category||brand||processor||pinoutsOnly)&&<button className="text-link" onClick={reset}>Reset device filters</button>}</div>
   <p className="search-hint">Use the search bar above. Try “T Embed”, “T-Beam”, “LoRa”, or a manufacturer. Partial connector maps and supporting references keep their own labels.</p>
   <div className="result-toolbar"><span aria-live="polite"><b>{matches.length}</b> devices with saved references{query&&<> matching <strong>“{query}”</strong></>}</span></div>
   {matches.length?<div className="board-grid">{matches.slice(0,limit).map(b=><div className="device-result" key={b.id}><BoardCard board={b} favorite={favorites.includes(b.id)} toggleFavorite={toggleFavorite} open={()=>open(b)}/><div className="device-record-label"><span>{b.device.category}</span>{b.device.phase==='in-development'&&<span className="development-label">Pre-release documentation</span>}</div></div>)}</div>:<div className="empty-state"><Search size={28}/><h3>No device references match these filters.</h3><p>Try another model name or clear a filter. Missing pinout sheets are tracked below.</p><button className="secondary-button" onClick={reset}>Reset device filters</button></div>}
   {matches.length>limit&&<div className="load-more"><button className="secondary-button" onClick={()=>setLimit(n=>n+30)}>Show 30 more</button><span>Showing {limit} of {matches.length}</span></div>}
  </section>
  <section className="device-watchlist"><div className="section-heading"><div><div className="eyebrow"><Clock size={14}/>DOCUMENTATION WATCH</div><h2>New hardware. Open questions.</h2></div></div><p>Published products and in-development projects whose exact pinout image is still missing or needs verification. These entries are excluded from the saved-reference counts. Availability is not inferred from a repository date.</p><div className="watchlist-grid">{watchlist.map(b=><article key={b.id}><span className="watch-status">{b.status}</span><h3>{b.name}</h3><div className="card-brand">{b.brand} · {b.processor||'Processor not verified'}</div><p>{b.note}</p><SourceLink url={b.source}>Official documentation</SourceLink><small>Documentation checked {b.checked}</small></article>)}</div>{!watchlist.length&&<p>No documentation-watch entries match this search.</p>}<p className="coverage-footnote">This is an expanding collection, not a complete inventory of every device ever made. A recorded source is not a bench test or permission to reprint manufacturer artwork.</p></section>
 </div>;
}
