import React,{useMemo,useState,useEffect,useRef} from 'react';
import {Search,X,ArrowUpRight} from 'lucide-react';
import {searchCatalog} from './global-search.mjs';
import {CoverageBadge} from './PinReference.jsx';
export default function GlobalSearch({catalog,query,setQuery,inputRef,openResult}){
 const [open,setOpen]=useState(false),[active,setActive]=useState(0),[scope,setScope]=useState('all'),[pinoutsOnly,setPinoutsOnly]=useState(false);const root=useRef(null);
 const all=useMemo(()=>searchCatalog(catalog,query,{scope,pinoutsOnly}),[catalog,query,scope,pinoutsOnly]);const results=all.slice(0,30);
 useEffect(()=>setActive(0),[query,scope,pinoutsOnly]);
 useEffect(()=>{if(open)root.current?.querySelector('#global-result-'+active)?.scrollIntoView({block:'nearest'});},[active,open]);
 useEffect(()=>{const handler=e=>{if(!root.current?.contains(e.target))setOpen(false);};document.addEventListener('pointerdown',handler);return()=>document.removeEventListener('pointerdown',handler);},[]);
 function pick(result){setOpen(false);openResult(result);}
 return <div className="global-search-wrap" ref={root}><div className="global-search"><Search size={20}/><input ref={inputRef} value={query} onFocus={()=>setOpen(true)} onChange={e=>{setQuery(e.target.value);setOpen(true);}} placeholder="Search every board, display, sensor or pin…" aria-label="Search boards and references" role="combobox" aria-expanded={open&&!!query.trim()} aria-controls="global-search-results" aria-autocomplete="list" aria-activedescendant={open&&results[active]?'global-result-'+active:undefined} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);return;}if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();setOpen(true);setActive(i=>Math.max(0,Math.min(results.length-1,i+(e.key==='ArrowDown'?1:-1))));}if(e.key==='Enter'&&open&&results[active]){e.preventDefault();pick(results[active]);}}}/>{query?<button className="icon-button" aria-label="Clear search" onClick={()=>{setQuery('');inputRef.current?.focus();}}><X size={17}/></button>:<kbd>Ctrl K</kbd>}</div>{open&&query.trim()&&<div className="global-search-panel"><div className="global-search-controls"><label>Search in <select aria-label="Global search scope" value={scope} onChange={e=>setScope(e.target.value)}><option value="all">Entire catalog</option><option value="boards">Boards & devices</option><option value="makers">Displays, sensors & modules</option></select></label><label><input type="checkbox" checked={pinoutsOnly} onChange={e=>setPinoutsOnly(e.target.checked)}/>Pinout sources only</label><button className="icon-button" aria-label="Close search results" onClick={()=>setOpen(false)}><X size={18}/></button></div><div className="global-search-count" role="status">{all.length} matching listings · exact models first</div><div id="global-search-results" role="listbox" aria-label="Search the entire catalog">{results.map((r,i)=><button type="button" role="option" aria-selected={i===active} id={'global-result-'+i} key={r.kind+r.record.id} className="global-search-result" onPointerMove={()=>setActive(i)} onClick={()=>pick(r)}><div><small>{r.record.brand} / {r.record.category||r.record.family}</small><b>{r.record.name}</b><CoverageBadge record={r.record}/></div><ArrowUpRight size={18}/></button>)}</div>{!all.length&&<p className="global-search-empty">No exact catalog match. Try the printed model code, a shorter query or another scope. Different revisions are kept separate.</p>}{all.length>30&&<p className="global-search-empty">Showing the first 30 matches. Add a manufacturer or model code to narrow the results.</p>}</div>}</div>;
}
